---
title: "Hyperbolic Discounting Comparison"
author: "Marcus Holloway"
date: "11/3/2021"
output: html_document
---

```{r}
library(pacman)

p_load(dplyr)

Inconsistency_test = function(reward,cost,discount){

  ##Determine first period choice given costs, rewards, and discount level for different discounting functions
  
  #beta = discount, t = payoff time, tau = planning time
  ######################
  
  # Period 1
  
  ## exponential discounting beta^t
  
  rperiod1ex1 = -cost[1]+(discount)*reward[2]+(discount^2)*reward[3]+(discount^3)*reward[4]
  
  rperiod2ex1 = reward[1]-(discount)*cost[2]+(discount^2)*reward[3]+(discount^3)*reward[4]
  
  rperiod3ex1 = reward[1]+(discount)*reward[2]-(discount^2)*cost[3]+(discount^3)*reward[4]
  
  rperiod4ex1 = reward[1]+(discount)*reward[2]+(discount^2)*reward[3]-(discount^3)*cost[4]
  
  ##Tie catch
  
  exptie1 = data.frame(period = c(1,2,3,4), vals = c(rperiod1ex1,rperiod2ex1,rperiod3ex1,rperiod4ex1))
  
  exptie1 = filter(exptie1, vals >=max(vals))
  
  expdec1 = ifelse(exptie1$period[1] == 1,1,
                   ifelse(exptie1$period[1] ==2,2,
                         ifelse(exptie1$period[1] == 3,3,4)))
  
  
  ## inconsistent hyperbolic discounting 1/(1+beta(t-tau))
  
  rperiod1ihyp1 = -cost[1]+(1/(1+discount))*reward[2]+(1/(1+discount*2))*reward[3]+(1/(1+discount*3))*reward[4]
  
  rperiod2ihyp1 = reward[1]-(1/(1+discount))*cost[2]+(1/(1+discount*2))*reward[3]+(1/(1+discount*3))*reward[4]
  
  rperiod3ihyp1 = reward[1]+(1/(1+discount))*reward[2]-(1/(1+discount*2))*cost[3]+(1/(1+discount*3))*reward[4]
  
  rperiod4ihyp1 = reward[1]+(1/(1+discount))*reward[2]+(1/(1+discount*2))*reward[3]-(1/(1+discount*3))*cost[4]
  
  
  # Tie Catch
  
  ihyptie1 = data.frame(period = c(1,2,3,4), vals = c(rperiod1ihyp1,rperiod2ihyp1,rperiod3ihyp1,rperiod4ihyp1))
  
  ihyptie1 = filter(chyptie1, vals >=max(vals))
  
  ihypdec1 = ifelse(ihyptie1$period[1] == 1,1,
                   ifelse(ihyptie1$period[1] ==2,2,
                         ifelse(ihyptie1$period[1] == 3,3,4)))
  
  
  ## consistent hyperbolic discounting (1+beta*tau)/(1+beta*t)
  
  rperiod1chyp1 = (-cost[1]) + (((1+discount)/(1+discount*2))*reward[2]) + (((1+discount)/(1+discount*3))*reward[3]) + (((1+discount)/(1+discount*4))*reward[4])
  
  rperiod2chyp1 = (reward[1]) - (((1+discount)/(1+discount*2))*cost[2]) + (((1+discount)/(1+discount*3))*reward[3]) + (((1+discount)/(1+discount*4))*reward[4])
  
  rperiod3chyp1 = (reward[1]) + (((1+discount)/(1+discount*2))*reward[2]) - (((1+discount)/(1+discount*3))*cost[3]) + (((1+discount)/(1+discount*4))*reward[4])
  
  rperiod4chyp1 = (reward[1]) + (((1+discount)/(1+discount*2))*reward[2]) + (((1+discount)/(1+discount*3))*reward[3]) - (((1+discount)/(1+discount*4))*cost[4])
  
  
   # Tie Catch
  
  chyptie1 = data.frame(period = c(1,2,3,4), vals = c(rperiod1chyp1,rperiod2chyp1,rperiod3chyp1,rperiod4chyp1))
  
  chyptie1 = filter(chyptie1, vals >=max(vals))
  
  chypdec1 = ifelse(chyptie1$period[1] == 1,1,
                   ifelse(chyptie1$period[1] ==2,2,
                         ifelse(chyptie1$period[1] == 3,3,4)))
  
  
  
  ## Each gives period 1 decision. If reward chosen in 1, decision making over. Report decision as 1, can not determine inconsistency.
  
  
  
  #######################
  
  # Period 2
  
   ## exponential discounting beta^t
  
  rperiod2ex2 = -cost[2]+(discount)*reward[3]+(discount^2)*reward[4]
  
  rperiod3ex2 = reward[2]-(discount)*cost[3]+(discount^2)*reward[4]
  
  rperiod4ex2 = reward[2]+(discount)*reward[3]-(discount^2)*cost[4]
  
  
   # Tie Catch
  
  exptie2 = data.frame(period = c(2,3,4), vals = c(rperiod2ex2,rperiod3ex2,rperiod4ex2))
  
  exptie2 = filter(exptie2, vals >=max(vals))
  
  expdec2 = ifelse(expdec1 == 1,1,
                   ifelse(exptie2$period[1] ==2,2,
                         ifelse(exptie2$period[1] == 3,3,4)))
  
  ## inconsistent hyperbolic discounting 1/(1+beta(t-tau))
  
  
  rperiod2ihyp2 = -cost[2] + (1/(1+discount))*reward[3]+ (1/(1+discount*2))*reward[4]
  
  rperiod3ihyp2 = reward[2] - (1/(1+discount))*cost[3] + (1/(1+discount*2))*reward[4]
  
  rperiod4ihyp2 = reward[2] +(1/(1+discount))*reward[3] - (1/(1+discount*2))*cost[4]
  
  # Tie Catch
  
  ihyptie2 = data.frame(period = c(2,3,4), vals = c(rperiod2ihyp2,rperiod3ihyp2,rperiod4ihyp2))
  
  ihyptie2 = filter(ihyptie2, vals >=max(vals))
  
  ihypdec2 = ifelse(ihypdec1 == 1,1,
                   ifelse(ihyptie2$period[1] ==2,2,
                         ifelse(ihyptie2$period[1] == 3,3,4)))
  
  
  ## consistent hyperbolic discounting (1+beta*tau)/(1+beta*t)
  
  
  rperiod2chyp2 = -cost[2] + (((1+2*discount)/(1+discount*3))*reward[3]) + (((1+2*discount)/(1+discount*4))*reward[4])
  
  rperiod3chyp2 = reward[2] - (((1+2*discount)/(1+discount*3))*cost[3]) + (((1+2*discount)/(1+discount*4))*reward[4])
  
  rperiod4chyp2 = reward[2] + (((1+2*discount)/(1+discount*3))*reward[3]) - (((1+2*discount)/(1+discount*4))*cost[4])
  
   # Tie Catch
  
  chyptie2 = data.frame(period = c(2,3,4), vals = c(rperiod2chyp2,rperiod3chyp2,rperiod4chyp2))
  
  chyptie2 = filter(chyptie2, vals >=max(vals))
  
  chypdec2 = ifelse(chypdec1 == 1,1,
                   ifelse(chyptie2$period[1] ==2,2,
                         ifelse(chyptie2$period[1]== 3,3,4)))

 
  
  #############
  
  
  # Period 3 & 4
    
    ## exponential discounting beta^t
  
  rperiod3ex3 = -cost[3]+(discount)*reward[4]
  
  rperiod4ex3 = reward[3]-(discount)*cost[4]
  
  
  # Tie Catch
  
  exptie3= data.frame(period = c(3,4), vals = c(rperiod3ex3,rperiod4ex3))
  
  exptie3 = filter(exptie2, vals >=max(vals))
  
  expdec3 = ifelse(expdec1 == 1,1,
                   ifelse(expdec2 == 2,2,
                         ifelse(exptie3$period[1] == 3,3,4)))
  
  expdec4 = ifelse(expdec3 ==1,1,
                   ifelse(expdec3 ==2,2,
                          ifelse(expdec3 ==3,3,4)))
  
  ## inconsistent hyperbolic discounting 1/(1+beta(t-tau))
  
  rperiod3ihyp3 = -cost[3]+(1/(1+discount))*reward[4]
  
  rperiod4ihyp3 = reward[3]-(1/(1+discount))*cost[4]
  
 # Tie Catch
  
  ihyptie3= data.frame(period = c(3,4), vals = c(rperiod3ihyp3,rperiod4ihyp3))
  
  ihyptie3 = filter(ihyptie2, vals >=max(vals))
  
  ihypdec3 = ifelse(ihypdec2== 1,1,
                   ifelse(ihypdec2 == 2,2,
                         ifelse(ihyptie3$period[1] == 3,3,4)))
  
  ihypdec4 = ifelse(ihypdec3 ==1,1,
                   ifelse(ihypdec3 ==2,2,
                          ifelse(ihypdec3 ==3,3,4)))
  
   ## consistent hyperbolic discounting (1+beta*tau)/(1+beta*t)
  
  
  rperiod3chyp3 = -cost[3]+((1+3*discount)/(1+discount*4))*reward[4]
  
  rperiod4chyp3 = reward[3]-((1+3*discount)/(1+discount*4))*cost[4]
  
   # Tie Catch
  
  chyptie3= data.frame(period = c(3,4), vals = c(rperiod3chyp3,rperiod4chyp3))
  
  chyptie3 = filter(chyptie2, vals >=max(vals))
  
  chypdec3 = ifelse(chypdec2 == 1,1,
                   ifelse(chypdec2 == 2,2,
                         ifelse(chyptie3$period[1] == 3,3,4)))
  
  chypdec4 = ifelse(chypdec1 ==1,1,
                   ifelse(chypdec2 ==2,2,
                          ifelse(chypdec3 ==3,3,4)))
  
  ## Put together results
  
  expdec = c(expdec1,expdec2,expdec3,expdec4)
  
  ihypdec = c(ihypdec1,ihypdec2,ihypdec3,ihypdec4)
  
  chypdec = c(chypdec1,chypdec2,chypdec3,chypdec4)
  
  dec = data.frame(exponential = expdec, inconsistent = ihypdec, consistent = chypdec)
    
  
if(length(unique(dec$inconsistent)) == 1){
    print("Decisions are time consistent for 1/(1+beta*(t-tau)")
} else{
    print("Decisions are not time consistent for 1/(1+beta*(t-tau)")
}
  
if(length(unique(dec$consistent)) == 1){
    print("Decisions are time consistent for (1+ beta*tau)/(1+beta*t)")
} else{
    print("Decisions are not time consistent for (1+ beta*tau)/(1+beta*t)")
}
  
return(dec)
  
}


## Check if working

Inconsistency_test(c(4,4,4,4),c(3,2,9,18),0.75)

## Mimics movie example in O'Donaghue and Raibin 1999. 3 of 4 periods a reward is chosen while 1 period a cost must be taken.

## Values in column indicate when costly action is planned to be taken

## Exp and consistent should always return the same value, inconsistent may not

```

```{r}

## Show consistency and inconsistency for multiple reward and cost schemes

co = expand.grid(1:13,1:13,1:13,1:13)

costs = c()

for(i in 1:nrow(co)){
  tem = list(c(co$Var1[i],co$Var2[i],co$Var3[i],co$Var4[i]))
  
  costs = append(costs,tem)
  
}

costs = data.frame(costs = I(costs))


hold = c()

for(i in 1:nrow(costs)){
 new = ifelse(length(unique(Inconsistency_test(c(1,1,1,1),as.vector(costs$costs[[i]]),0.5)[,3]))==1,T,F)
  
  hold = c(hold,new)
}

costs$reward1discount0.5 = hold

hold2 = c()

for(i in 1:nrow(costs)){
 new = ifelse(length(unique(Inconsistency_test(c(1,1,1,1),as.vector(costs$costs[[i]]),0.5)[,2]))==1,T,F)
  
  hold2 = c(hold2,new)
}

costs$reward1discount0.5inconsistent = hold2

hold3 = c()

for(i in 1:nrow(costs)){
 new = ifelse(length(unique(Inconsistency_test(c(1,1,1,1),as.vector(costs$costs[[i]]),0.5)[,1]))==1,T,F)
  
  hold3 = c(hold3,new)
}

costs$reward1discount0.5ex = hold3


```

